/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KnowledgeSlugRouteImport } from './routes/knowledge.$slug'
import { Route as ClaimCategoryRouteImport } from './routes/claim.$category'
import { Route as ApiTranscribeAudioRouteImport } from './routes/api/transcribe-audio'
import { Route as AnalysisDisputeIdRouteImport } from './routes/analysis.$disputeId'

const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeSlugRoute = KnowledgeSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => KnowledgeRoute,
} as any)
const ClaimCategoryRoute = ClaimCategoryRouteImport.update({
  id: '/claim/$category',
  path: '/claim/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeAudioRoute = ApiTranscribeAudioRouteImport.update({
  id: '/api/transcribe-audio',
  path: '/api/transcribe-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisDisputeIdRoute = AnalysisDisputeIdRouteImport.update({
  id: '/analysis/$disputeId',
  path: '/analysis/$disputeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/analysis/$disputeId': typeof AnalysisDisputeIdRoute
  '/api/transcribe-audio': typeof ApiTranscribeAudioRoute
  '/claim/$category': typeof ClaimCategoryRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/analysis/$disputeId': typeof AnalysisDisputeIdRoute
  '/api/transcribe-audio': typeof ApiTranscribeAudioRoute
  '/claim/$category': typeof ClaimCategoryRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/analysis/$disputeId': typeof AnalysisDisputeIdRoute
  '/api/transcribe-audio': typeof ApiTranscribeAudioRoute
  '/claim/$category': typeof ClaimCategoryRoute
  '/knowledge/$slug': typeof KnowledgeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/knowledge'
    | '/analysis/$disputeId'
    | '/api/transcribe-audio'
    | '/claim/$category'
    | '/knowledge/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/knowledge'
    | '/analysis/$disputeId'
    | '/api/transcribe-audio'
    | '/claim/$category'
    | '/knowledge/$slug'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/knowledge'
    | '/analysis/$disputeId'
    | '/api/transcribe-audio'
    | '/claim/$category'
    | '/knowledge/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  AnalysisDisputeIdRoute: typeof AnalysisDisputeIdRoute
  ApiTranscribeAudioRoute: typeof ApiTranscribeAudioRoute
  ClaimCategoryRoute: typeof ClaimCategoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge/$slug': {
      id: '/knowledge/$slug'
      path: '/$slug'
      fullPath: '/knowledge/$slug'
      preLoaderRoute: typeof KnowledgeSlugRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/claim/$category': {
      id: '/claim/$category'
      path: '/claim/$category'
      fullPath: '/claim/$category'
      preLoaderRoute: typeof ClaimCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe-audio': {
      id: '/api/transcribe-audio'
      path: '/api/transcribe-audio'
      fullPath: '/api/transcribe-audio'
      preLoaderRoute: typeof ApiTranscribeAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/$disputeId': {
      id: '/analysis/$disputeId'
      path: '/analysis/$disputeId'
      fullPath: '/analysis/$disputeId'
      preLoaderRoute: typeof AnalysisDisputeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface KnowledgeRouteChildren {
  KnowledgeSlugRoute: typeof KnowledgeSlugRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeSlugRoute: KnowledgeSlugRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  AnalysisDisputeIdRoute: AnalysisDisputeIdRoute,
  ApiTranscribeAudioRoute: ApiTranscribeAudioRoute,
  ClaimCategoryRoute: ClaimCategoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
